#
# Module manifest for module 'MPTool'
#
# Generated by: Martin Arnoldi @ CasaMDA & Andreas Sobczyk @ CloudMechanic.net
#
# Generated on: 05/12/2015
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'MPTool.psm1'

# Version number of this module.
ModuleVersion = '1.0.7.0'

# ID used to uniquely identify this module
GUID = '7a5b9fc0-886b-4802-a02f-a575d5872448'

# Author of this module
Author = 'Martin Arnoldi @ CasaMDA & Andreas Sobczyk @ CloudMechanic.net'

# Company or vendor of this module
CompanyName = 'CasaMDA & CloudMechanic.net'

# Copyright statement for this module
Copyright = '(c) 2015 Martin Arnoldi @ CasaMDA & Andreas Sobczyk @ CloudMechanic.net. All rights reserved.'

# Description of the functionality provided by this module
# Description = 'https://github.com/AndreasSobczyk/MPTool'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of the .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @('OperationsManager')

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @()

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module.
ModuleList = @('MPTool.psm1')

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
# HelpInfoURI = 'https://github.com/AndreasSobczyk/MPTool/wiki'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

